export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const TOGGLE_ALL = 'TOGGLE_ALL'
export const SWITCH_FILTER = 'SWITCH_FILTER'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
